using System.Text.Json;
using System.Text.Json.Serialization;

using Shimakaze.Milky.Model;
using Shimakaze.Milky.Model.Api.File;
using Shimakaze.Milky.Model.Api.Friend;
using Shimakaze.Milky.Model.Api.Group;
using Shimakaze.Milky.Model.Api.Message;
using Shimakaze.Milky.Model.Api.System;
using Shimakaze.Milky.Model.Common;
using Shimakaze.Milky.Model.Event;
using Shimakaze.Milky.Model.Message;

namespace Shimakaze.Milky;

[JsonSourceGenerationOptions(WriteIndented = false)]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(MilkyResult))]

[JsonSerializable(typeof(CreateGroupFolderInput))]
[JsonSerializable(typeof(CreateGroupFolderOutput))]
[JsonSerializable(typeof(DeleteGroupFileInput))]
[JsonSerializable(typeof(DeleteGroupFolderInput))]
[JsonSerializable(typeof(GetGroupFileDownloadUrlInput))]
[JsonSerializable(typeof(GetGroupFileDownloadUrlOutput))]
[JsonSerializable(typeof(GetGroupFilesInput))]
[JsonSerializable(typeof(GetGroupFilesOutput))]
[JsonSerializable(typeof(GetPrivateFileDownloadUrlInput))]
[JsonSerializable(typeof(GetPrivateFileDownloadUrlOutput))]
[JsonSerializable(typeof(MoveGroupFileInput))]
[JsonSerializable(typeof(RenameGroupFileInput))]
[JsonSerializable(typeof(RenameGroupFolderInput))]
[JsonSerializable(typeof(UploadGroupFileInput))]
[JsonSerializable(typeof(UploadGroupFileOutput))]
[JsonSerializable(typeof(UploadPrivateFileInput))]
[JsonSerializable(typeof(UploadPrivateFileOutput))]
[JsonSerializable(typeof(AcceptFriendRequestInput))]
[JsonSerializable(typeof(GetFriendRequestsOutput))]
[JsonSerializable(typeof(GetFriendRequestsInput))]
[JsonSerializable(typeof(RejectFriendRequestInput))]
[JsonSerializable(typeof(SendFriendNudgeInput))]
[JsonSerializable(typeof(SendProfileLikeInput))]
[JsonSerializable(typeof(AcceptGroupInvitationInput))]
[JsonSerializable(typeof(AcceptGroupRequestInput))]
[JsonSerializable(typeof(DeleteGroupAnnouncementInput))]
[JsonSerializable(typeof(GetGroupAnnouncementListInput))]
[JsonSerializable(typeof(GetGroupAnnouncementListOutput))]
[JsonSerializable(typeof(GetGroupEssenceMessagesInput))]
[JsonSerializable(typeof(GetGroupEssenceMessagesOutput))]
[JsonSerializable(typeof(GetGroupNotificationsInput))]
[JsonSerializable(typeof(GetGroupNotificationsOutput))]
[JsonSerializable(typeof(KickGroupMemberInput))]
[JsonSerializable(typeof(QuitGroupInput))]
[JsonSerializable(typeof(RejectGroupInvitationInput))]
[JsonSerializable(typeof(RejectGroupRequestInput))]
[JsonSerializable(typeof(SendGroupAnnouncementInput))]
[JsonSerializable(typeof(SendGroupMessageReactionInput))]
[JsonSerializable(typeof(SendGroupNudgeInput))]
[JsonSerializable(typeof(SetGroupAvatarInput))]
[JsonSerializable(typeof(SetGroupEssenceMessageInput))]
[JsonSerializable(typeof(SetGroupMemberAdminInput))]
[JsonSerializable(typeof(SetGroupMemberCardInput))]
[JsonSerializable(typeof(SetGroupMemberMuteInput))]
[JsonSerializable(typeof(SetGroupMemberSpecialTitleInput))]
[JsonSerializable(typeof(SetGroupNameInput))]
[JsonSerializable(typeof(SetGroupWholeMuteInput))]
[JsonSerializable(typeof(GetForwardedMessagesInput))]
[JsonSerializable(typeof(GetForwardedMessagesOutput))]
[JsonSerializable(typeof(GetHistoryMessagesInput))]
[JsonSerializable(typeof(GetHistoryMessagesOutput))]
[JsonSerializable(typeof(GetMessageInput))]
[JsonSerializable(typeof(GetMessageOutput))]
[JsonSerializable(typeof(GetResourceTempUrlInput))]
[JsonSerializable(typeof(GetResourceTempUrlOutput))]
[JsonSerializable(typeof(MarkMessageAsReadInput))]
[JsonSerializable(typeof(RecallGroupMessageInput))]
[JsonSerializable(typeof(RecallPrivateMessageInput))]
[JsonSerializable(typeof(SendGroupMessageInput))]
[JsonSerializable(typeof(SendGroupMessageOutput))]
[JsonSerializable(typeof(SendMessageApiCommonOutput))]
[JsonSerializable(typeof(SendPrivateMessageInput))]
[JsonSerializable(typeof(SendPrivateMessageOutput))]
[JsonSerializable(typeof(GetCookiesInput))]
[JsonSerializable(typeof(GetCookiesOutput))]
[JsonSerializable(typeof(GetCSRFTokenOutput))]
[JsonSerializable(typeof(GetFriendInfoInput))]
[JsonSerializable(typeof(GetFriendInfoOutput))]
[JsonSerializable(typeof(GetFriendListInput))]
[JsonSerializable(typeof(GetFriendListOutput))]
[JsonSerializable(typeof(GetGroupInfoInput))]
[JsonSerializable(typeof(GetGroupInfoOutput))]
[JsonSerializable(typeof(GetGroupListInput))]
[JsonSerializable(typeof(GetGroupListOutput))]
[JsonSerializable(typeof(GetGroupMemberInfoInput))]
[JsonSerializable(typeof(GetGroupMemberInfoOutput))]
[JsonSerializable(typeof(GetGroupMemberListInput))]
[JsonSerializable(typeof(GetGroupMemberListOutput))]
[JsonSerializable(typeof(GetImplInfoOutput))]
[JsonSerializable(typeof(GetLoginInfoOutput))]
[JsonSerializable(typeof(GetUserProfileInput))]
[JsonSerializable(typeof(GetUserProfileOutput))]
[JsonSerializable(typeof(FriendCategoryEntity))]
[JsonSerializable(typeof(FriendEntity))]
[JsonSerializable(typeof(FriendRequest))]
[JsonSerializable(typeof(GroupAdminChangeNotification))]
[JsonSerializable(typeof(GroupAnnouncementEntity))]
[JsonSerializable(typeof(GroupEntity))]
[JsonSerializable(typeof(GroupFileEntity))]
[JsonSerializable(typeof(GroupFolderEntity))]
[JsonSerializable(typeof(GroupInvitedJoinRequestNotification))]
[JsonSerializable(typeof(GroupJoinRequestNotification))]
[JsonSerializable(typeof(GroupKickNotification))]
[JsonSerializable(typeof(GroupMemberEntity))]
[JsonSerializable(typeof(GroupNotification))]
[JsonSerializable(typeof(GroupQuitNotification))]
[JsonSerializable(typeof(Event))]
[JsonSerializable(typeof(FaceSegmentData))]
[JsonSerializable(typeof(ForwardSegmentData))]
[JsonSerializable(typeof(FriendMessage))]
[JsonSerializable(typeof(GroupEssenceMessage))]
[JsonSerializable(typeof(GroupMessage))]
[JsonSerializable(typeof(ImageSegmentData))]
[JsonSerializable(typeof(IncomingForwardedMessage))]
[JsonSerializable(typeof(IncomingMessage))]
[JsonSerializable(typeof(IncomingSegment))]
[JsonSerializable(typeof(MentionSegmentData))]
[JsonSerializable(typeof(OutgoingForwardedMessage))]
[JsonSerializable(typeof(OutgoingSegment))]
[JsonSerializable(typeof(ReplySegmentData))]
[JsonSerializable(typeof(SharedSegment))]
[JsonSerializable(typeof(TempMessage))]
[JsonSerializable(typeof(TextSegmentData))]
[JsonSerializable(typeof(VideoSegmentData))]
public sealed partial class MilkyJsonSerializerContext : JsonSerializerContext
{
}
