using Humanizer;

using Milky.Net.ModelGenerator.Models;

namespace Milky.Net.ModelGenerator;

internal static class MilkyCSharpApiTypeGenerator
{
    public static IEnumerable<(string TypeName, string Code)> MakeClients(IEnumerable<ApiCategory> categories)
    {
        List<string> properties = [];
        List<string> constructor = [];

        foreach (var category in categories)
        {
            var clientPropertyName = category.Key.Pascalize();
            var clientTypeName = $"Milky{clientPropertyName}Client";
            properties.Add($$"""
                /// <inheritdoc cref="{{clientTypeName}}" />
                public {{clientTypeName}} {{clientPropertyName}} { get; }
            """);
            constructor.Add($"{clientPropertyName} = new(this);");

            using StringWriter client = new();
            client.WriteLine($$"""
                // Generated by Milky.Net.ModelGenerator
                //      ❤️ from frg2089
                
                using Milky.Net.Model;
                        
                #nullable enable
                        
                namespace Milky.Net.Client;
                        
                /// <summary>
                /// {{category.Name}}
                /// </summary>
                /// <param name="client"></param>
                public sealed class {{clientTypeName}}
                {
                    private readonly MilkyClient _client;
                
                    internal {{clientTypeName}}(MilkyClient client)
                        => _client = client;
                """);

            foreach (var api in category.Apis)
            {
                var requestTypeName = "object";
                var parameter = string.Empty;
                var argument = "MilkyClient.EmptyObject";
                if (api.RequestFields is { Count: not 0 })
                {
                    requestTypeName = $"{api.Endpoint}Request".Pascalize();
                    parameter = $"{requestTypeName} input, ";
                    argument = "input";
                }

                var responseTypeName = "object";
                var returnType = "Task";
                if (api.ResponseFields is { Count: not 0 })
                {
                    responseTypeName = $"{api.Endpoint}Response".Pascalize();
                    returnType = $"Task<{responseTypeName}>";
                }

                client.WriteLine($$"""

                        /// <summary>
                        /// {{api.Description}}
                        /// </summary>
                        /// <remarks>
                        /// 详见文档 <see href="https://milky.ntqqrev.org/api/{{category.Key}}#{{api.Endpoint}}"/>
                        /// </remarks>
                        public async {{returnType}} {{api.Endpoint.Pascalize()}}Async({{parameter}}CancellationToken cancellationToken = default)
                            => await _client.RequestAsync<{{requestTypeName}}, {{responseTypeName}}>("{{api.Endpoint}}", {{argument}}, cancellationToken);
                    """);
            }
            client.WriteLine("}");

            yield return (clientTypeName, client.ToString());
        }

        yield return ("MilkyClient", $$"""
        // Generated by Milky.Net.ModelGenerator
        //      ❤️ from frg2089
        
        using System.Collections.Immutable;
        using System.Linq;
        
        #nullable enable
        
        namespace Milky.Net.Client;
        
        public sealed partial class MilkyClient
        {
            /// <summary>
            /// 创建 Milky 客户端
            /// </summary>
            /// <param name="client">Http 客户端实例</param>
            /// <param name="middleware">请求中间件</param>
            /// <param name="eventSchedulerProvider">事件调度器，默认为<cref="MilkyEventScheduler"/></param>
            /// <param name="eventLogger">SSE日志记录器</param>
            public MilkyClient(
                HttpClient client,
                IEnumerable<IMilkyClientMiddleware>? middleware = default,
                IMilkyEventSchedulerProvider? eventSchedulerProvider = null,
                Microsoft.Extensions.Logging.ILogger<IMilkyEventScheduler>? eventLogger = null)
            {
                _client = client;
                _middleware = middleware?.Reverse().ToImmutableArray() ?? [];
                eventSchedulerProvider ??= MilkyEventSchedulerProvider.Default;
                Events = eventSchedulerProvider.Create(this);
                _eventLogger = eventLogger;
                {{constructor.Join("\r\n        ")}}
            }

        {{properties.Join("\r\n")}}
        }
        """);
    }

    public static void MakeEventScheduler(AdvancedUnionType eventType, out string eventSchedulerCode, out string interfaceCode)
    {
        using StringWriter eventWriter = new();
        using StringWriter switchWriter = new();

        foreach (var item in eventType.DerivedTypes)
        {
            var pascal = item.TagValue.Pascalize();

            var typeName = item is RefDerivedType refDerivedType
                ? refDerivedType.RefStructName.Pascalize()
                : $"{pascal}EventData";

            eventWriter.WriteLine($"""
                    
                    /// <inheritdoc cref="{typeName}" />
                    public event ReceivedEventHandler<Event<{typeName}>>? {pascal};
                """);
            switchWriter.WriteLine($"""

                            case Event<{typeName}> e:
                                {pascal}?.Invoke(_client, e);
                                return;
                """);
        }

        interfaceCode = $$"""
        // Generated by Milky.Net.ModelGenerator
        //      ❤️ from frg2089

        using Milky.Net.Model;
                
        #nullable enable

        namespace Milky.Net.Client;

        public partial interface IMilkyEventScheduler
        {{{eventWriter}}
        }
        """;

        eventSchedulerCode = $$"""
            // Generated by Milky.Net.ModelGenerator
            //      ❤️ from frg2089

            using Milky.Net.Model;
                    
            #nullable enable

            namespace Milky.Net.Client;
            
            public sealed partial class MilkyEventScheduler
            {{{eventWriter}}
                    
                public partial void Received(Event @event)
                {
                    switch (@event)
                    {{{switchWriter}}
                    }
                }
            }
            """;
    }

    public static IEnumerable<(string TypeName, string Code)> MakeServerApiEndpoints(IEnumerable<ApiCategory> categories)
    {
        List<string> registryConstructorArguments = [];
        List<string> endpointNames = [];
        using StringWriter registryConstructor = new()
        {
            NewLine = "\r\n" + new string(' ', 4 * 2)
        };
        using StringWriter registryFields = new()
        {
            NewLine = "\r\n" + new string(' ', 4 * 1)
        };
        using StringWriter registrySwitchCases = new()
        {
            NewLine = "\r\n" + new string(' ', 4 * 3)
        };

        foreach (var category in categories)
        {
            var pascalCategory = category.Key.Pascalize();
            var camelCategory = pascalCategory.Camelize();
            var fieldName = $"_{camelCategory}";
            var typeName = $"IMilky{pascalCategory}ApiEndpoints";

            registryFields.WriteLine($"private readonly {typeName} {fieldName};");
            registryConstructorArguments.Add($"{typeName} {camelCategory}");
            registryConstructor.WriteLine($"{fieldName} = {camelCategory};");

            using StringWriter sw = new()
            {
                NewLine = "\r\n" + new string(' ', 4 * 1)
            };
            foreach (var api in category.Apis)
            {
                var requestTypeName = string.Empty;
                var parameter = string.Empty;
                if (api.RequestFields is { Count: not 0 })
                {
                    requestTypeName = $"{api.Endpoint}Request".Pascalize();
                    parameter = $"{requestTypeName} input, ";
                }

                var responseTypeName = string.Empty;
                var returnType = "Task";
                if (api.ResponseFields is { Count: not 0 })
                {
                    responseTypeName = $"{api.Endpoint}Response".Pascalize();
                    returnType = $"Task<{responseTypeName}>";
                }

                sw.WriteLine(
                    $$"""

                        /// <summary>
                        /// {{api.Description}} <br />
                        /// 详见文档 <see href="https://milky.ntqqrev.org/api/{{category.Key}}#{{api.Endpoint}}"/>
                        /// </summary>
                        [ApiEndpoint("{{api.Endpoint}}")]
                        {{returnType}} {{api.Endpoint.Pascalize()}}Async({{parameter}}CancellationToken cancellationToken = default);
                    """);

                endpointNames.Add(api.Endpoint);
                registrySwitchCases.WriteLine($"case \"{api.Endpoint}\":");
                registrySwitchCases.NewLine = "\r\n" + new string(' ', 4 * 4);
                registrySwitchCases.WriteLine("{");
                if (!string.IsNullOrEmpty(requestTypeName))
                {
                    registrySwitchCases.WriteLine($"Debug.Assert(json is not null);");
                    registrySwitchCases.WriteLine($"var input = json.Value.Deserialize(MilkyJsonSerializerContext.Default.{requestTypeName});");
                    registrySwitchCases.WriteLine($"Debug.Assert(input is not null);");
                }
                if (!string.IsNullOrEmpty(responseTypeName))
                    registrySwitchCases.Write($"var output = ");
                registrySwitchCases.Write($"await {fieldName}.{api.Endpoint.Pascalize()}Async(");
                if (!string.IsNullOrEmpty(requestTypeName))
                    registrySwitchCases.Write("input, ");
                registrySwitchCases.WriteLine("cancellationToken);");
                registrySwitchCases.NewLine = "\r\n" + new string(' ', 4 * 3);
                if (!string.IsNullOrEmpty(responseTypeName))
                    registrySwitchCases.WriteLine($"return (output, MilkyJsonSerializerContext.Default.{responseTypeName});");
                else
                    registrySwitchCases.WriteLine($"return null;");
                registrySwitchCases.WriteLine("}");
            }

            yield return (
                typeName,
                $$"""
                // Generated by Milky.Net.ModelGenerator
                //      ❤️ from frg2089
                
                using Milky.Net.Model;

                #nullable enable

                namespace Milky.Net.Server;
                        
                /// <summary>
                /// {{category.Name}}
                /// </summary>
                public interface {{typeName}}
                {{{sw}}
                }
                """);
        }

        yield return (
            "MilkyApiEndpoints",
            $$"""
            // Generated by Milky.Net.ModelGenerator
            //      ❤️ from frg2089
                    
            using System.Diagnostics;
            using System.Text.Json;
            using System.Text.Json.Serialization.Metadata;
                    
            using Milky.Net.Model;
                    
            #nullable enable
                    
            namespace Milky.Net.Server;

            /// <summary>
            /// Milky API 端点
            /// </summary>
            public partial class MilkyApiEndpoints
            {
                {{registryFields}}

                /// <summary>
                /// 创建 Milky API 端点处理器
                /// </summary>
                public MilkyApiEndpoints({{string.Join(", ", registryConstructorArguments)}})
                {
                    {{registryConstructor}}
                }
                    
                /// <summary>
                /// 尝试匹配 API 端点
                /// </summary>
                public bool CanInvoke(string endpoint) => endpoint switch
                {
                    {{string.Join(" or ", endpointNames.Select(i => $"\"{i}\""))}} => true,
                    _ => false,
                };

                /// <summary>
                /// 调度 API 请求
                /// </summary>
                public async Task<(object Result, JsonTypeInfo Type)?> InvokeAsync(string endpoint, JsonElement? json, CancellationToken cancellationToken = default)
                {
                    switch(endpoint)
                    {
                        {{registrySwitchCases}}
                    }
                    return null;
                }
            }
            """);
    }
}
