using System.Text.Json;

using DotMake.CommandLine;

using Milky.Net.ModelGenerator.Models;
using Milky.Net.SourceGenerator.Common;

namespace Milky.Net.ModelGenerator;

[CliCommand(Parent = typeof(GenerateCommand))]
internal sealed class ModelsCommand
{
    [CliOption(Required = true)]
    public required FileInfo Source { get; set; }

    [CliOption(Required = true)]
    public required DirectoryInfo Output { get; set; }

    public async Task RunAsync()
    {
        if (Output.Exists)
            Output.Delete(true);
        Output.Create();

        MilkyIR milkyIR;
        await using (var fs = Source.OpenRead())
        {
            var json = await JsonSerializer.DeserializeAsync(fs, MilkyJsonSerializerContext.Default.JsonElement);
            milkyIR = MilkyIR.ParseFromJson(json);
        }

        var types = MilkyCSharpModelTypeGenerator.Parse(milkyIR).DistinctBy(static i => i is ModelClassBuilder { TypeParams: { Count: not 0 } typeParams }
                ? $"{i.Name}{string.Join(", ", typeParams.Select(static i => $"T{i.Name}"))}"
                : i.Name);

        await using var jsonSerializerContext = File.CreateText(Path.Combine(Output.FullName, "MilkyJsonSerializerContext.g.cs"));

        await jsonSerializerContext.WriteLineAsync("""
            using System.Text.Json;
            using System.Text.Json.Serialization;

            #nullable enable

            namespace Milky.Net.Model;

            [global::System.Text.Json.Serialization.JsonSourceGenerationOptions(WriteIndented = false)]
            [global::System.Text.Json.Serialization.JsonSerializable(typeof(object))]
            [global::System.Text.Json.Serialization.JsonSerializable(typeof(System.Text.Json.JsonElement))]
            [global::System.Text.Json.Serialization.JsonSerializable(typeof(MilkyResult))]
            """);

        foreach (var type in types)
        {
            var fileName = type.Name;
            if (type is ModelClassBuilder { TypeParams: { Count: not 0 } typeParams })
                fileName += $"{{{string.Join(", ", typeParams.Select(static i => $"T{i.Name}"))}}}";
            else
                await jsonSerializerContext.WriteLineAsync($"[global::System.Text.Json.Serialization.JsonSerializable(typeof({type.Name}))]");

            await File.WriteAllTextAsync(
                Path.Combine(Output.FullName, $"{fileName}.g.cs"),
                $"""
                // Generated by Milky.Net.ModelGenerator
                //      ❤️ from frg2089

                #nullable enable

                namespace Milky.Net.Model;

                {type.Build()}
                """);
        }

        await jsonSerializerContext.WriteLineAsync("""
            public sealed partial class MilkyJsonSerializerContext : global::System.Text.Json.Serialization.JsonSerializerContext
            {
            }
            """);

        await jsonSerializerContext.FlushAsync();
    }
}
