name: 检查 @saltify/milky-types 更新

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  check:
    name: 检查更新
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 签出仓库
        uses: actions/checkout@v5
        with:
          sparse-checkout: |-
            tools/schema-generator

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: 获取最新版本
        id: fetch
        # 这该死的 pnpm outdated 在发现版本过期时会报 1 退出码
        # https://github.com/pnpm/pnpm/pull/2718
        continue-on-error: true
        shell: pwsh
        run: |-
          $OutdatedList = pnpm outdated '@saltify/milky-types' --json --filter=@milky.net/schema-generator | ConvertFrom-Json
          $Info = $OutdatedList.'@saltify/milky-types'
          "outdated=$($Info.latest -ne $Info.wanted)" >> $env:GITHUB_OUTPUT
          "latest=$($Info.latest)" >> $env:GITHUB_OUTPUT
          "current=$($Info.wanted)" >> $env:GITHUB_OUTPUT

      - name: 创建分支
        if: ${{ steps.fetch.outputs.outdated == 'True' }}
        shell: pwsh
        run: |-
          git switch --force-create 'update/${{ steps.fetch.outputs.latest }}'
          git push origin 'update/${{ steps.fetch.outputs.latest }}' --force

      - name: 更新 @saltify/milky-types
        if: ${{ steps.fetch.outputs.outdated == 'True' }}
        shell: pwsh
        run: pnpm add "@saltify/milky-types@${{ steps.fetch.outputs.latest }}" --filter=@milky.net/schema-generator

      - name: 提交和推送
        if: ${{ steps.fetch.outputs.outdated == 'True' }}
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |-
          $tmp = '${{ github.repository }}' -split '/'
          pnpm dlx @pirafrank/github-commit-sign commit `
            --owner $tmp[0] `
            --repo $tmp[1] `
            --branch 'update/${{ steps.fetch.outputs.latest }}' `
            --changed 'tools/schema-generator/package.json' `
            --changed 'pnpm-lock.yaml' `
            --commitMessage 'Update @saltify/milky-types' `
            --commitDescription 'Current: ${{ steps.fetch.outputs.current }}`nLatest: ${{ steps.fetch.outputs.latest }}'

      - name: 创建拉取请求
        if: ${{ steps.fetch.outputs.outdated == 'True' }}
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
            gh pr create `
              --title "Update @saltify/milky-types to ${{ steps.fetch.outputs.latest }}" `
              --body "Current: ${{ steps.fetch.outputs.current }}`n`nLatest: ${{ steps.fetch.outputs.latest }}" `
              --base 'master'